services:
  redis:
    image: redis:5.0.7-alpine
    networks:
      - harvest-sudoc-network

  dashboard:
    image: dataesr/dashboard-crawler:1.1
    ports:
      - 9181:9181
    command: rq-dashboard -H redis
    networks:
      - harvest-sudoc-network
    depends_on:
      - redis
  
  mongo:
    image: mongo:4.0.0
    ports:
      - 27017:27017
    volumes:
      - '/tmp/mongodb:/tmp/mongodb'
    networks:
      - harvest-sudoc-network

  worker:
    image: ghcr.io/dataesr/harvest-sudoc:0.0.0
    privileged: true
    command: >
      /bin/sh -c "sysctl -w vm.max_map_count=262144
      && python3 manage.py run_worker"
    environment:
      APP_SETTINGS: project.server.config.DevelopmentConfig
    volumes:
      - '/tmp/.X11-unix:/tmp/.X11-unix'
    networks:
      - harvest-sudoc-network
    depends_on:
      - redis
      - mongo

  web:
    build: .
    privileged: true
    ports:
      - 5004:5000
    command: python3 manage.py run -h 0.0.0.0
    environment:
      FLASK_DEBUG: 1
      APP_SETTINGS: project.server.config.DevelopmentConfig
      APP_ENV: 'development'
    volumes:
      - '/tmp/.X11-unix:/tmp/.X11-unix'
    networks:
      - harvest-sudoc-network
    depends_on:
      - worker

networks:
  harvest-sudoc-network:
    driver: bridge